# Generated by Django 6.0.6 on 2026-06-23 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_portfolio', '0002_achievements_alter_experience_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manage_portfolio.profile'),
            preserve_default=False,
        ),
    ]
